"""Changed the model for testing

Revision ID: 14381365f352
Revises: 6625a87746dd
Create Date: 2025-12-28 01:37:55.734845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14381365f352'
down_revision = '6625a87746dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp_earned', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_xp', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_xp')
        batch_op.drop_column('level')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('xp_earned')

    # ### end Alembic commands ###
